# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='fileOrig',
            field=models.FileField(upload_to='upload/uploadFiles/'),
        ),
    ]
