# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20170417_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='fileOrig',
            field=models.FileField(upload_to='upload/files/'),
        ),
    ]
