# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='fileOrig',
            field=models.CharField(max_length=100),
        ),
    ]
